version: '2.1'

services:

  test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn test-watch
    volumes:
      - c2s-test-node_modules:/code/node_modules
      - .:/code
    links:
      - nearby-services-api:nearby-services-api

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-ci
    user: root
    volumes:
      - c2s-test-ci-node_modules:/code/node_modules
    environment:
      API_BASE_URL: 'http://nearby-services-api:3001'
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - nearby-services-api:nearby-services-api

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${NEARBY_SERVICES_API_DOCKER_IMAGE_TAG-0.13.0}"
    links:
      - pharmacy-db-elastic:es

  pharmacy-db-elastic:
    image: "nhsuk/elasticsearch-updater-snapshot:20170921"

volumes:
  c2s-test-node_modules:
  c2s-test-ci-node_modules:
